### PR TITLE
Fix graphical data source for bigmap

### PR DESCRIPTION
**Pull request by aronson**
Credit to NeoTechni from the GBADEV Discord.

Context:
image

### CODE REVIEW

**Comment by AntonioND** [comment]
It looks good to me, I'll let others have the chance to take a look at it before I merge it.

**Comment by AntonioND** [comment]
When I build the ROM with the new image, I get this:

bigmap-0

Can you take a look at it and make sure it builds correctly?

**Review by AntonioND — CHANGES_REQUESTED** [review]
Check that the example works correctly with the new image.

**Comment by aronson** [comment]
I opened this PR for someone else and don't have capacity to test. Closing. I hope they learn how to open one and make the changes, otherwise the errors are documented here.

**Pull request closed without merging**
